version: "3"
services:
  redis:
    restart: always
    image: redis:alpine
    volumes:
      - redis-data:/data

  edgedb:
    restart: always
    image: edgedb/edgedb:4.1
    volumes:
      - edgedb-data:/var/lib/edgedb/data:/var/lib/edgedb/data
      - "./dbschema:/dbschema"
    env_file:
      - .env

  minio:
    restart: always
    image: minio/minio:latest
    command: server --address ":9000" /data/
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - minio-storage:/data

  app:
    restart: always
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      - redis
      - edgedb

    env_file:
      - .env

  worker:
    restart: always
    build:
      context: .
      dockerfile: background.Dockerfile
    depends_on:
      - redis
      - edgedb

    env_file:
      - .env

volumes:
  redis-data:
  edgedb-data:
  minio-storage: