# AUTOGENERATED FROM:
#     'dbschema/queries/create_lecture.edgeql'
#     'dbschema/queries/get_lecture.edgeql'
#     'dbschema/queries/set_lecture_status.edgeql'
# WITH:
#     $ edgedb-py --file app/queries.py


from __future__ import annotations
import dataclasses
import edgedb
import enum
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateLectureResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetLectureResult(NoPydanticValidation):
    id: uuid.UUID
    status: LectureStatus
    filename: str


class LectureStatus(enum.Enum):
    CREATED = "Created"
    PROCESSING = "Processing"
    PROCESSED = "Processed"


async def create_lecture(
    executor: edgedb.AsyncIOExecutor,
    *,
    filename: str,
) -> CreateLectureResult:
    return await executor.query_single(
        """\
        insert Lecture {
            filename := <str>$filename
        };\
        """,
        filename=filename,
    )


async def get_lecture(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> GetLectureResult | None:
    return await executor.query_single(
        """\
        select Lecture {
            id,
            status,
            filename
        }
        filter .id = <uuid>$id
        limit 1\
        """,
        id=id,
    )


async def set_lecture_status(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    status: str,
) -> CreateLectureResult | None:
    return await executor.query_single(
        """\
        update Lecture
        filter .id = <uuid>$id
        set {
            status := <str>$status
        }\
        """,
        id=id,
        status=status,
    )
